verify_on_Scroll:
	forge verify-contract 0x133555dB8bD881890e3f86e6a39Ad622620BaB13 backend/solidity/contracts/erc20.sol:SampleERC20 --verifier-url https://api-sepolia.scrollscan.com/api --api-key XN5VTWB95ZTFMNITS4KVWS29T1J62UFIJE

hardhat_verify:
	npx hardhat verify --network scrollSepolia 0x133555dB8bD881890e3f86e6a39Ad622620BaB13 <param_1> <param_2>
